pip install click
pip install pyshp
pip install shapefile
pip install pandas
pip install PyGeoj
pip install numpy
pip install xarray
pip install sqlite3
pip install csv
pip install scipy
pip install geojson
pip install gdal
pip install pytest
pip install jsonlib
